#include "pico/stdlib.h"
#include "ice_cram.h"
#include "ice_fpga.h"

// Include the bitstream generated by the build process
uint8_t bitstream[] = {
#include "bitstream.h"
};

int main(void) {
    // 1. Initialize Standard IO
    stdio_init_all();

    // 2. Configure the FPGA Clock to 48 MHz
    // This matches the CLOCK_FREQUENCY parameter in your top.sv
    ice_fpga_init(FPGA_DATA, 48); 
    ice_fpga_start(FPGA_DATA);

    // 3. Load the Bitstream into the FPGA
    ice_cram_open(FPGA_DATA);
    ice_cram_write(bitstream, sizeof(bitstream));
    ice_cram_close();

    // 4. Infinite Loop
    // The FPGA is running independently now. The MCU does nothing.
    while (true) {
        tight_loop_contents(); // Low-power idle
    }
}